### ISSUE TITLE
Nice going.. 

### ISSUE THREAD

**Issue by godbless876** [JessyJP/ReaStreamMobile#1]
Awesome... But.. is there a way I can get to test this out... I don't see an app release.

If could code I would have done an app already... Thanks for your
 https://github.com/niusounds/libReaStream
 This is the other project I am following...

**Comment by JessyJP** [comment]
Thank you for your interest in the app.
My aim is to make it real-time capable. 

I checked out the other project but I couldn't compile it and it seems it was last made and major updated 7 or so years ago with some recent updates which I will check again when I have time.

About the alpha release
[ReaStreamMobile_AlphaRelease.zip](https://github.com/JessyJP/ReaStreamMobile/files/8877717/ReaStreamMobile_AlphaRelease.zip)

About the Alpha Release:
---------------------------
1) Audio only. 
2) Reception only.
3) Mono channel works successfully on my setup.
4) Stereo has noise, most likely due to network latency on my phone only supporting WiFi5. That will be tested with an ethernet adapter when I get one.
5) I have disabled device selection so it will play on the default audio output, which is not bad at all actually, however, I don't know how that will behave with Bluetooth headphones in general. 

-------------------------------------------
I have tested: 
* the phone's inbuilt speakers; 
* headphones with a USB DAC connected; 
* Roland UA25EX audio interface (non-ASIO/Advanced driver option); 
* It didn't work with my Bluetooth earphones.

[ReaStreamMobile_AlphaTest.zip](https://github.com/JessyJP/ReaStreamMobile/files/8877706/ReaStreamMobile_AlphaTest.zip)

**Comment by godbless876** [comment]
Awesome... U are the best... Gonna try it out . Do you think it can handle multiple connections?

**Comment by godbless876** [comment]
So. Yes I tried it out and yes.. the latency is good... Gonna try it with a different router to see if it works better... But it's better than the other app and the web control is soooooooo cool.. thanks for implementing that... 
A few things I noticed tho... The app resets once it's closed.. probably an option to load or save certain settings would be great.. . Also.. if the screen rotates the audio goes out and  I would have to toggle the RX button to get sound again... Also as u had mentioned.. only single channel audio works good... But it's better than none

**Comment by JessyJP** [comment]
- There will be an option to select different UI looks/ profiles because people might want to use it with their organization and put logo etc and limit certain functions. 

- The control comes from reaper but I will post a script and update that adds the tempo next to the measure.
I will make that available in a separate repository and also talk to the guys in Raper to add it by default.

- There will be more setup options, such as devices, drivers and sample rates for the output.

- There is an option to keep the audio in the background but I didn't enable that yet, it will be in the next release probably. 

- Many musicians are still using mono monitors, if I manage to optimise it enough it may be possible to run as an in-ear monitor, actually, I have tested the app can receive data before it reaches the audio interface so they are not interdependent. (Speaking of which, I will try to develop a plugin that allows adding other audio interfaces for output/monitoring while keeping them independent.)

**Comment by JessyJP** [comment]
> Awesome... U are the best... Gonna try it out . Do you think it can handle multiple connections?

Yes! But we have to define what we mean here. The host can easily handle multiple connections. The client can handle only 1 connection at the time and that's all you need becuase the client is a terminal to the input and output. 

For example, think conference translation. Multiple people can be routed to the preferred output broadcast. Therefore, you can have say 5 outbound broadcasts (languages) and 50 clients, i.e. 10 of each. While you mix the original speaker with the corresponding translation in any DAW/VST host effectively.

**Comment by godbless876** [comment]
The part about adding interfaces

**Comment by JessyJP** [comment]
> The part about adding interfaces

Ah, I see. The principle is the same to the mobile app itself as it is not running on the same device or driver. 
If we attach multiple devices but run them on different(individual drivers), especially if it's only for output there shouldn't be any problems with clock sync issues, mainly if we are limited to ASIO outputs only we can tolerate imperceptible buffer resets or occasional glitches. At the same time, we can ensure sub-millisecond buffer transfers.
I will start a new Github repository for a DAW plugin that will effectively allow instantaneous buffer transfer from one DAW to another and test how that works.

**Comment by godbless876** [comment]
Yeah. That would be awesome... Something like asio4all but better... Or my favorite.. synchronous audio router.. it creates virtual ins and outs and u can create as many as needed but they need to be tied to hardware ...  I can currently use it to get individual outs and it  could work with ur app.. but the latency is too much for live music...am really really excited about what ur doing... And the idea Of the plugin that could host/add multiple interfaces longside  the main asio driver is beautiful... If I knew how to code I would help.... But I do love to test new tech so am always here for that..

**Comment by JessyJP** [comment]
I will be switching the sound engine to Oboe there might be some good improvementes in the near future.

**Comment by godbless876** [comment]
Ok. Awesome.. looking forward to testing ..

**Comment by godbless876** [comment]
Hey..I was trying to use the app and the part where I should input the IP address is really small... I can't see what I type... Probably you could work on that also...

**Comment by JessyJP** [comment]
For fixes, bugs, and feature requests could you please open a separate issue for each!
Also, you might be interested in the new open issue which references another repository that will work with this app.
